# Generated by Django 2.0.3 on 2018-03-27 17:11

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '轮播商品',
                'verbose_name': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('goods_sn', models.CharField(help_text='商品唯一货号', max_length=80, verbose_name='商品编码')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('goods_detail', DjangoUeditor.models.UEditorField(blank=True, help_text='商品详情富文本', null=True, verbose_name='商品详情')),
                ('image', models.ImageField(help_text='商品图片路劲', max_length=200, upload_to='Goods/%Y/%m/', verbose_name='商品展示图片')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='是否免邮')),
                ('market_price', models.FloatField(default=0, verbose_name='市场价')),
                ('shop_price', models.FloatField(default=0, verbose_name='促销价')),
                ('sales_volume', models.IntegerField(default=0, verbose_name='销量')),
                ('goods_nums', models.IntegerField(default=0, verbose_name='商品数量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsBannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='商品轮播图片路劲', max_length=200, upload_to='GoodsBanner/%Y/%m/', verbose_name='商品图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '商品展示图片',
                'verbose_name': '商品展示图片',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=50, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别名code', max_length=30, verbose_name='类别名code')),
                ('desc', models.CharField(default='', help_text='类别描述', max_length=120, verbose_name='类别描述')),
                ('category_type', models.CharField(choices=[('1', '一级类名'), ('2', '二级类名'), ('3', '三级类名')], default='1', help_text='类别级别', max_length=5, verbose_name='类别级别')),
                ('is_table', models.BooleanField(default=False, verbose_name='是否放入首页导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类类别')),
            ],
            options={
                'verbose_name_plural': '商品类别',
                'verbose_name': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('image', models.ImageField(upload_to='brand/%Y/%m', verbose_name='品牌名图片路径')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '品牌名',
                'verbose_name': '品牌名',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
    ]
