# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页商品轮播', 'verbose_name_plural': '首页商品轮播'},
        ),
    ]
