# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180328_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(help_text='商品图片路劲', max_length=200, upload_to='goods/images/', verbose_name='商品展示图片'),
        ),
    ]
