# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180328_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '购物车订单商品', 'verbose_name_plural': '购物车订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单详情', 'verbose_name_plural': '订单详情'},
        ),
    ]
